<?php

namespace App\Support;

class AdsPlan
{
    /**
     * Specialty residential ads plan: homeowners only, four material campaigns.
     *
     * @return array<string, mixed>
     */
    public static function make(): array
    {
        return [
            'meta' => [
                'title' => 'Residential ads plan',
                'prepared' => 'Sep 21, 2026',
                'filename' => 'core-four-residential-ads-plan-2026.pdf',
                'focus' => 'Homeowners · Houston suburb ring · specialty materials only',
            ],
            'assumptions' => [
                'cpc' => '$18 blended specialty Search',
                'cvr' => '7.5% click → lead',
                'cpl' => '$240–$360 modeled',
                'qualified' => '80%',
                'close' => '20% of qualified · ~16% of all leads',
                'ticket' => '$22,000 blended',
                'first_month' => 'CPL +25% in days 15–45',
            ],
            'campaigns' => [
                [
                    'slug' => 'tile',
                    'name' => 'Tile roof repairs & replacements',
                    'share' => '30%',
                    'volume' => 'High among the four',
                    'ticket' => '$6k repair · $22–40k replace',
                    'why' => 'Houston’s 1990s–2000s master-planned homes are hitting the age when concrete and clay tile fails — broken tiles, failed underlayment, valley leaks. Core Four already proved the story: the Jul 30 botched-tile post was the top Facebook piece this year.',
                    'where' => 'The Woodlands, Katy, Fulshear, Cinco Ranch, Sugar Land, Richmond, Missouri City, Sienna.',
                    'queries' => [
                        'tile roof repair',
                        'clay tile roof repair',
                        'concrete tile roof repair',
                        'tile roof replacement',
                        'broken tile roof',
                        'leaking tile roof',
                        'spanish tile roof repair',
                        'tile roofing contractor + city',
                    ],
                    'landing' => '/residential-roofing/roof-repair/',
                    'landing_note' => 'Build a dedicated tile page before scaling. Until then: roof-repair with tile RSA + sitelinks.',
                    'landing_needed' => true,
                ],
                [
                    'slug' => 'scs',
                    'name' => 'Stone-coated steel repairs & replacements',
                    'share' => '20%',
                    'volume' => 'Low search, high ticket',
                    'ticket' => '$24–45k replace',
                    'why' => 'The upgrade pitch when tile is too heavy, too brittle, or too expensive to re-do. Same look, a fraction of the weight, and it handles Houston hail. People search the brand names more than the category.',
                    'where' => 'Same tile-heavy west and Woodlands zips — often the replacement for a failing tile roof.',
                    'queries' => [
                        'stone coated steel roof',
                        'stone coated steel replacement',
                        'decra roof / decra roofing',
                        'metal tile roof',
                        'lightweight tile roof',
                        'gerard roof',
                        'replace tile with metal',
                    ],
                    'landing' => '/residential-roofing/stone-coated-steel/',
                    'landing_note' => 'Live page. Send every SCS ad here — not the homepage.',
                    'landing_needed' => false,
                ],
                [
                    'slug' => 'metal',
                    'name' => 'Metal roofing repairs & replacements',
                    'share' => '40%',
                    'volume' => 'Highest of the four',
                    'ticket' => '$5k repair · $18–38k standing seam',
                    'why' => 'The volume engine. Standing-seam and residential metal already have a live page, photos, and search demand. This campaign funds the plan so tile, SCS, and slate can stay tight.',
                    'where' => 'North ring first (Tomball, Woodlands, Cypress, Spring), then west. Skip barn / shop / metal-building queries.',
                    'queries' => [
                        'metal roof replacement',
                        'standing seam metal roof',
                        'residential metal roof',
                        'metal roof repair',
                        'metal roof leak',
                        'metal roofing contractor + city',
                    ],
                    'landing' => '/residential-roofing/metal-roofs/',
                    'landing_note' => 'Live page. Residential standing seam only — never commercial metal.',
                    'landing_needed' => false,
                ],
                [
                    'slug' => 'slate',
                    'name' => 'Slate roof repairs & replacements',
                    'share' => '10%',
                    'volume' => 'Scarce · keep exact/phrase',
                    'ticket' => '$8k repair · $35–70k replace',
                    'why' => 'Few Houston roofers will touch real slate well. Volume is thin; the ticket is not. One or two jobs a year can cover months of this ad group. Do not expand match types to chase volume.',
                    'where' => 'Woodlands custom, Memorial Villages, and similar estate pockets inside the suburb ring. Not downtown. Not a statewide blast.',
                    'queries' => [
                        'slate roof repair',
                        'slate roof replacement',
                        'slate roofing contractor',
                        'leaking slate roof',
                        'natural slate roof',
                    ],
                    'landing' => '/residential-roofing/',
                    'landing_note' => 'Build a dedicated slate page before spending more than a test. Until then: residential hub with slate RSA.',
                    'landing_needed' => true,
                ],
            ],
            'tiers' => [
                [
                    'label' => 'Test',
                    'amount' => '$2,000',
                    'period' => 'per month · north ring · Metal + Tile only',
                    'mix' => [
                        ['name' => 'Search', 'share' => 90, 'dollars' => '$1,800'],
                        ['name' => 'Remarketing', 'share' => 10, 'dollars' => '$200'],
                    ],
                    'on' => 'Metal and Tile search in Tomball, The Woodlands, Cypress, Spring, Humble.',
                    'off' => 'SCS, Slate, Meta, CTV, west and south rings.',
                    'clicks' => '50–70',
                    'leads' => '4–6',
                    'qualified' => '3–5',
                    'jobs_90' => '1–2',
                    'jobs_year' => '6–10',
                    'media_job' => '$2,400–$4,000',
                    'revenue' => '$130k–$220k',
                    'note' => 'Two campaigns only. $2k cannot feed four specialty ad groups without starving Metal and Tile.',
                ],
                [
                    'label' => 'Recommended',
                    'amount' => '$5,000',
                    'period' => 'per month · north + west · all four campaigns',
                    'featured' => true,
                    'mix' => [
                        ['name' => 'Search', 'share' => 70, 'dollars' => '$3,500'],
                        ['name' => 'Remarketing', 'share' => 10, 'dollars' => '$500'],
                        ['name' => 'Meta', 'share' => 20, 'dollars' => '$1,000'],
                    ],
                    'on' => 'Metal 40% / Tile 30% / SCS 20% / Slate 10% of Search. North + Katy / Fulshear / Sugar Land.',
                    'off' => 'CTV, Austin, Dallas, downtown, generic shingle keywords.',
                    'clicks' => '120–165',
                    'leads' => '9–14',
                    'qualified' => '7–11',
                    'jobs_90' => '3–5',
                    'jobs_year' => '14–22',
                    'media_job' => '$2,700–$4,300',
                    'revenue' => '$310k–$485k',
                    'note' => 'Best start. Meta uses the tile-repair story and metal/SCS job photos in the same zips — not a Houston DMA blast.',
                ],
                [
                    'label' => 'Scale',
                    'amount' => '$10,000',
                    'period' => 'per month · full suburb ring + CTV',
                    'mix' => [
                        ['name' => 'Search', 'share' => 65, 'dollars' => '$6,500'],
                        ['name' => 'YouTube', 'share' => 10, 'dollars' => '$1,000'],
                        ['name' => 'Meta', 'share' => 15, 'dollars' => '$1,500'],
                        ['name' => 'CTV', 'share' => 10, 'dollars' => '$1,000'],
                    ],
                    'on' => 'All four campaigns across the suburb ring. CTV for homeowners who later search the brand.',
                    'off' => 'Last-click credit for CTV. Generic “roof replacement” still off.',
                    'clicks' => '220–290',
                    'leads' => '16–24',
                    'qualified' => '13–19',
                    'jobs_90' => '5–8',
                    'jobs_year' => '22–34',
                    'media_job' => '$3,500–$5,500',
                    'revenue' => '$485k–$750k',
                    'note' => 'Adds Pearland, League City, Friendswood, Pasadena. Cut south/east or CTV first if CPL slips — never cut Metal + Tile search.',
                ],
            ],
            'negatives' => [
                'asphalt', 'shingle', '3-tab', 'cheap', 'free', 'DIY', 'jobs', 'salary', 'apprentice',
                'commercial', 'TPO', 'EPDM', 'warehouse', 'property manager',
                'metal building', 'barn', 'shop', 'kit', 'Amazon',
                'Austin', 'Dallas', 'downtown', 'Houston roofer cheap',
            ],
            'dont' => [
                'Generic “roof replacement” / “roofers near me” as the core — that auction is cheap-shingle lead-gen.',
                'Asphalt or 3-tab keywords in this account.',
                'Commercial, TPO, warehouse, or property-manager language.',
                'Austin, Dallas, or inside-the-Loop targeting.',
                'Performance Max before form + call conversions are firing.',
                'Sending paid clicks to the homepage.',
                'Broad match before 50+ specialty conversions.',
                'Four campaigns live on a $2k budget.',
            ],
        ];
    }
}
